sudo: required
services: 
   - docker
   
before_install: 
   - docker build -t lohithgowda23/docker-react -f Dockerfile111.dev .

script: 
   - docker run lohithgowda23/docker-react npm run start -- --coverage
   
